# Competitor URLs for analysis
competitor_urls:
  marketplaces:
    - name: "Super Mix"
      url: "https://supermixstore.com/products/capa-de-sofa-premium-em-chenille-com-design-moderno-chumbo"

# SEO Configuration
seo_settings:
  primary_keywords:
    - "Capa de Sofa"
    - "Capa protetora de Sofá"
    - "Capa de Sofá de Luxo"
  secondary_keywords:
    - "capa de sofa premium"
    - "capa de sofa impermeabilizante"
  target_search_volume: 1000
  competition_level: "medium"

# Product Analysis Settings
product_analysis:
  min_reviews: 50
  min_rating: 4.0
  price_range:
    min: 10
    max: 100
  categories_to_analyze:
    - "category1"
    - "category2"