product:
  title: "Capa de Sofá Premium em Chenille com Design Moderno Chumbo"
  description: |
    <h1 style="text-align: left; margin-bottom: 2em;">Capa de Sofá Premium em Chenille com Design Moderno Chumbo</h1>

    <div style="margin: 2em 0; line-height: 1.6; text-align: left;">
    <p>Transforme seu sofá com nossa Capa Premium em Chenille - a solução perfeita para proteção e elegância. Confeccionada com tecido chenille de alta qualidade, esta capa oferece durabilidade excepcional e um toque luxuoso que complementa qualquer decoração.</p>

    <p>Com lentes de alta qualidade e armação premium, nossos óculos de sol oferecem proteção UV completa enquanto mantêm um visual distinto e atemporal. O design leve e resistente garante conforto durante o uso prolongado sem comprometer o estilo.</p>

    <p>Desenvolvidos com materiais de primeira linha e acabamento luxuoso, estes óculos são a escolha ideal para quem busca qualidade, elegância e proteção em uma única peça.</p>
    </div>

    <div style="margin: 2em 0; line-height: 1.6; text-align: left;">
    <h2 style="text-align: left; margin-bottom: 1.5em;">Por Que Nossos Óculos São a Escolha Perfeita para Suas Viagens?</h2>
    <p>Quando se trata de encontrar os óculos de sol ideais para suas viagens, cada detalhe importa. Nossa peça se destaca pela combinação única de design vintage, materiais premium e proteção avançada pensada para o viajante moderno. A armação ajustável e as hastes flexíveis garantem conforto excepcional, mesmo durante longos períodos de uso.</p>
    </div>

    <div style="margin: 2em 0; line-height: 1.6; text-align: left;">
    <h2 style="text-align: left; margin-bottom: 1.5em;">Tecnologia Avançada para Máxima Proteção e Estilo</h2>
    <p>Nossos óculos incorporam as mais recentes inovações em proteção ocular. As lentes com proteção UV400 bloqueiam 100% dos raios nocivos, enquanto o revestimento antirreflexo proporciona visão cristalina em qualquer condição de luz. A armação reforçada e as dobradiças de alta qualidade garantem anos de uso sem comprometer a integridade do produto.</p>
    </div>

    <div style="margin: 2em 0; line-height: 1.6; text-align: left;">
    <h2 style="text-align: left; margin-bottom: 1.5em;">Benefícios Exclusivos para Seu Estilo</h2>
    <ul style="list-style-type: none; padding-left: 0; text-align: left;">
      <li style="margin: 1em 0;"><strong>Design Vintage Atemporal</strong> - Estilo clássico que nunca sai de moda</li>
      <li style="margin: 1em 0;"><strong>Proteção Superior</strong> - Lentes UV400 com proteção total contra raios UVA e UVB</li>
      <li style="margin: 1em 0;"><strong>Durabilidade Premium</strong> - Construídos com materiais de alta qualidade para maior durabilidade</li>
      <li style="margin: 1em 0;"><strong>Versatilidade Total</strong> - Perfeitos para viagens, praia, direção e uso diário</li>
      <li style="margin: 1em 0;"><strong>Conforto Garantido</strong> - Design ergonômico para uso prolongado sem desconforto</li>
    </ul>
    </div>

    <div style="margin: 2em 0; line-height: 1.6; text-align: left;">
    <h2 style="text-align: left; margin-bottom: 1.5em;">Como Cuidar dos Seus Óculos de Sol</h2>
    <p>Maximize a durabilidade dos seus óculos de sol mantendo-os sempre limpos com o pano de microfibra incluso. Guarde-os no estojo protetor quando não estiver em uso e evite deixá-los expostos a temperaturas extremas. Para melhor conservação, limpe as lentes regularmente e manuseie a armação com cuidado.</p>
    </div>

    <div style="margin: 2em 0; line-height: 1.6; text-align: left;">
    <h2 style="text-align: left; margin-bottom: 1.5em;">Especificações Técnicas</h2>
    <table style="width: 100%; border-collapse: collapse; margin: 1em 0;">
      <tr><td style="padding: 0.5em 0; border-bottom: 1px solid #eee;"><strong>Material da Armação</strong></td><td style="padding: 0.5em 0; border-bottom: 1px solid #eee;">Acetato Premium</td></tr>
      <tr><td style="padding: 0.5em 0; border-bottom: 1px solid #eee;"><strong>Material das Lentes</strong></td><td style="padding: 0.5em 0; border-bottom: 1px solid #eee;">Policarbonato com Proteção UV400</td></tr>
      <tr><td style="padding: 0.5em 0; border-bottom: 1px solid #eee;"><strong>Peso</strong></td><td style="padding: 0.5em 0; border-bottom: 1px solid #eee;">28g</td></tr>
      <tr><td style="padding: 0.5em 0; border-bottom: 1px solid #eee;"><strong>Dimensões</strong></td><td style="padding: 0.5em 0; border-bottom: 1px solid #eee;">14.5 x 5.2 x 4.5 cm</td></tr>
    </table>
    </div>

    <div style="margin: 2em 0; line-height: 1.6; text-align: left;">
    <h4 style="text-align: left; margin-bottom: 1em;">📦 O Que Você Recebe:</h4>
    <ul style="list-style-type: none; padding-left: 0; text-align: left;">
      <li style="margin: 0.5em 0;">✓ 1x Óculos de Sol Vintage de Luxo</li>
      <li style="margin: 0.5em 0;">✓ 1x Estojo Protetor Premium</li>
      <li style="margin: 0.5em 0;">✓ 1x Pano de Limpeza de Microfibra</li>
      <li style="margin: 0.5em 0;">✓ Garantia de 1 ano</li>
    </ul>
    </div>

  seo:
    tags:
      - "Óculos de sol"
      - "Óculos de sol de viagem"
      - "Óculos de sol de Viagem de Luxo"
      - "óculos vintage"
      - "óculos de proteção UV"
    url_handle: "oculos-sol-vintage-luxo-viagem"

  variants:
    - color: "Preto Clássico"
      price: "199.90"
      sku: "OSV-PRE-001"

  inventory:
    track_inventory: true
    quantity: 50

  compare_at_price: "299.90"