---
create_structure_task:
  description: >
    Escreva um texto promocional sobre {NOME_DO_PRODUTO}, seguindo esta estrutura OBRIGATÓRIA:

    1️⃣ **Título Principal (H1)** - Nome do produto
    2️⃣ **Introdução** - 3 parágrafos curtos apresentando o produto
    3️⃣ **Por Que Escolher Este Produto? (H2)** - Diferencial competitivo
    4️⃣ **Tecnologia e Características (H2)** - Aspectos técnicos principais
    5️⃣ **Benefícios Exclusivos (H2)** - Lista com 4-5 benefícios chave
    6️⃣ **Como Usar/Aproveitar (H2)** - Instruções práticas
    7️⃣ **Especificações Técnicas (H2)** - Tabela com detalhes técnicos
    8️⃣ **O Que Você Recebe (H4)** - Lista de itens inclusos
    9️⃣ **Garantia e Suporte (H2)** - Informações de garantia
    🔟 **Avaliações e Depoimentos (H2)** - Prova social

    **Regras de Formatação:**
    - Margem de 2em entre seções
    - Alinhamento à esquerda
    - Line-height 1.6
    - Parágrafos com 3-4 frases
    - Listas sem bullets
    - Tabela para especificações
    - CTAs estratégicos
    - Elementos de prova social

    **Se o texto não seguir essa estrutura, será REJEITADO.**
  expected_output: Um texto bem estruturado, com espaçamento adequado, títulos e subtítulos bem definidos, incluindo elementos de prova social e CTAs estratégicos.
  async_execution: false
  agent: estrutura_organizer

generate_content_task:
  description: |
    Using the structure from create_structure_task, create a compelling, SEO-optimized product page that converts. Focus on:
    - Natural keyword integration throughout content
    - Clear value proposition and benefits
    - Persuasive product descriptions
    - Strategic placement of social proof
    - Compelling calls-to-action
    - Technical specifications accuracy
    - Mobile-friendly formatting
    - Customer testimonials integration
    - Guarantee and support details
  expected_output: A comprehensive, conversion-optimized product page that seamlessly integrates SEO elements while maintaining readability and engagement.
  async_execution: false
  agent: seo_copywriter
  context:
  - create_structure_task

review_content_task:
  description: |
    Perform a thorough quality check of the generated content, ensuring:
    - Perfect alignment with page structure requirements
    - Optimal keyword placement and density
    - Compelling and clear value proposition
    - Strategic CTA placement and effectiveness
    - Technical accuracy and specification validation
    - Social proof integration and authenticity
    - Mobile responsiveness of formatting
    - Grammar and clarity perfection
    - E-commerce best practices compliance
  expected_output: A polished, conversion-ready product page that excels in both technical SEO requirements and user experience.
  async_execution: false
  agent: content_editor
  context:
  - generate_content_task
